title: Huszics Márton
subtitle: Személyes oldalam
description: 'c:\\ismerteto.md Amire lehet, arra szoftvert írok.'
url: ''
baseurl: ''
urls:
  - text: Rólam
    url: /about
  - text: Írások
    url: /blog
  - text: Képek
    url: /gallery
  - text: Kapcsolat
    url: /contact
author_logo: profile.png
author: Huszics Márton
author_bio: >-
  Üdvözöllek. Huszics Márotn vagyok. Ezt az oldalt az informatikai
  tevékenységeim végett hoztam létre. Ha nem IT-val foglalkozok, akkor családommal töltöm az időt, tanítok, de gitározok, zenét szerzek, koncertet szervezek, önjelölt hangmérnök tevékenységet űzök. Érdekel a biztonságtechnika valamint Raspberry pi-vel építek otthoni megoldásokat. Ha még marad időm, akkor kicsit barkácsolok vagy szépítem a házunk.
author_email: huszicsmarton@gmail.com
author_location: 'Magyarország, Székesfehérvár'
author_website_url: 'https://huszicsmarton.github.io'
typewrite-text: 'c:\\ismerteto.md Amire lehet, arra szoftvert írok.'
author_work_experiences:
  - company_name: IBM
    company_logo: ibm.png
    company_url: 'https://www.ibm.com/'
    designation: Alkalmazás fejlesztő
    description: >-
      Workflow alapú alkalmazások fejlesztése. Front-end, back-end, adatbázis
      fejlesztés.
    visibility: true
  - company_name: Óbudai egyetem
    company_logo: oe.png
    company_url: 'http://www.amk.uni-obuda.hu/'
    designation: Órai elóadó
    description: '3 tantárgy oktatása: Android alkalmazás fejlesztés, iOS mobilalkalmazás fejlesztés, Felhőszolgáltatások elmélet és gyakorlat'
    visibility: true
author_education_details:
  - college_logo: ibm.png
    college_name: IBM
    college_url: 'https://www.youracclaim.com/badges/6ff74c1f-40c2-4bb3-86ad-60d99ee44b3f?source=linked_in_profile'
    college_degree: Containers & Kubernetes Essentials
    visibility: true
  - college_logo: ibm.png
    college_name: IBM
    college_url: 'https://www.youracclaim.com/badges/8a36b925-dd50-4869-a2a4-a408e91cd48f?source=linked_in_profile'
    college_degree: IBM Cloud Essentials v3
    visibility: true
  - college_logo: ibm.png
    college_name: IBM
    college_url: 'https://www.youracclaim.com/badges/5cb37633-2b83-43df-95e4-badf1636ca2e?source=linked_in_profile'
    college_degree: Cloud Core
    visibility: true
  - college_logo: cognitive_class.png
    college_name: Cognitive Class
    college_url: 'https://courses.cognitiveclass.ai/certificates/e2e0ea788db4413c9309215fdc01d6d7'
    college_degree: Introduction to Cloud
    visibility: true
  - college_logo: scademy.png
    college_name: Scademy
    college_url: 'https://cert.scademy.com/certificate/rcmzbCchXrCiXNkFvpMz'
    college_degree: Java and Web application security
    visibility: true
  - college_logo: na.png
    college_name: NetAcademia
    college_url: 'https://netacademia.hu/'
    college_degree: Node.js Application development
    visibility: true
  - college_logo: na.png
    college_name: Training360
    college_url: 'https://www.training360.com/'
    college_degree: Angular 2 plus framework
    visibility: true
  - college_logo: na.png
    college_name: Training360
    college_url: 'https://www.training360.com/'
    college_degree: Enterprise alkalmazásfejlesztés Java EE környezetben (JAVAX-EE)
    visibility: true
  - college_logo: oe.png
    college_name: 'Óbudai Egyetem, AREK'
    college_url: 'http://www.amk.uni-obuda.hu/'
    college_degree: 'Mérnök Informatikus, Hálózati rendszermérnök'
    visibility: true
author_project_details:
  - project_thumbnail: suliwebex.png
    project_title: Suliwebex.hu weboldal
    project_description: Kollégámmal valamint sok tartalomkészítővel közösen elkészítettük az oldalt, ami segítség az oktatásban.
    project_url: 'https://suliwebex.hu'
    visibility: true
  - project_thumbnail: ftv_android.jpg
    project_title: Fehérvár TV Android app
    project_description: >-
      Készítettem magamnak egy média lejátszót, ami a helyi hírekből
      táplálkozik.
    project_url: 'https://play.google.com/store/apps/details?id=devftv.mhusz.hu'
    visibility: true
github_username: humarci
facebook_username: marton.huszics
linkedin_username: márton-huszics-86379b4a
hyvor_talk_website_id:
mailchimp_form_url: >-
  https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0
formspree_code: f/xeqpyepj
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts
  files_to_exclude: []
  nodes_to_index: article
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
collections:
  - products
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: ./build
